spring.application.name=gym_app

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gym_app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gym_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.profiles.active=local

security.jwt.secret=${SECURITY_JWT_SECRET:dev-only-secret-change-me-later-123456}
security.jwt.expiration=${SECURITY_JWT_EXPIRATION:3600000}

